#!/bin/sh
# Mutations lock per message; local viewing controls remain available.
set -eu
{
node --input-type=module <<'CONFIG'
const base=process.env.DESIGN_BASE_URL;if(!/^http:\/\/localhost:\d+$/.test(base||''))throw Error('Use isolated localhost');console.log('const config='+JSON.stringify({base,space:Number(process.env.EGO_TASK_SPACE),root:process.cwd()})+';');
CONFIG
cat <<'JS'
const fs=await import('node:fs/promises'),assert=(await import('node:assert/strict')).default;const t=await taskSpace(config.space),p=t.page('p1'),out=config.root+'/docs/design/execution/evidence/ai-chat-readonly';await fs.mkdir(out,{recursive:true});
const rows=Array.from({length:15},(_,i)=>'记录'+(i+1));
const form=`Form("data",Buttons([Button("提交当前信息",Action([@ToAssistant("提交")]))]),[FormControl("文本",Input("text","请输入","text",null,"原值")),FormControl("选择",Select("choice",[SelectItem("a","选项A"),SelectItem("b","选项B")],"请选择",null,"a")),Slider("range","continuous",0,100,1,[30],"数值"),CheckBoxGroup("checks",[CheckBoxItem("勾选","说明","one",true)]),RadioGroup("radio",[RadioItem("单选A","","a"),RadioItem("单选B","","b")],"a"),SwitchGroup("switch",[SwitchItem("开关","说明","toggle",true)]),Chips("chips","single",[ChipItem("a","标签A"),ChipItem("b","标签B")]),OptionCards("options","single",[OptionCard("a","卡片A"),OptionCard("b","卡片B")]),DatePicker("date","single",null,"2026-10-05")])`;
const response=`root = Stack([${form}, EditableTable("records",[{type:"text",key:"text",header:"编辑内容"}],[{id:"a",values:["第一条"]},{id:"b",values:["第二条"]}]),Tabs([TabItem("one","视图一",[TextContent("第一视图")]),TabItem("two","视图二",[TextContent("第二视图")])]),Table([Col("记录",${JSON.stringify(rows)}),Col("宽列",${JSON.stringify(rows.map(()=> '需要左右滚动才能查看的完整数据'.repeat(4)))} )]),Accordion([AccordionItem("info","查看说明",[TextContent("展开后的说明")])]),CodeBlock("text","可查看和复制的内容")])`;
const fixture={id:'readonly-fixture',agentId:'general',title:'历史只读检查',messages:[{id:'old',role:'assistant',parts:[{type:'text',text:response}]},{id:'question',role:'user',parts:[{type:'text',text:'继续'}]},{id:'latest',role:'assistant',parts:[{type:'text',text:response}]}]};
await p.goto(config.base+'/robots.txt');await p.evaluate(c=>{const k='personal-design:ai-chat:v1';if(JSON.parse(localStorage.getItem(k)||'{}').conversations?.some(x=>!['readonly-fixture','case-fixture','component-fixture','contract-fixture'].includes(x.id)))throw Error('User records');localStorage.setItem(k,JSON.stringify({agents:[],conversations:[c]}));},fixture);await p.goto(config.base+'/products/ai-chat');await p.waitForSelector('.ai-openui[data-read-only]');
const reveal=selector=>p.evaluate(selector=>{const el=document.querySelector(selector),s=document.querySelector('[aria-label="对话"]>div');s.scrollTop+=el.getBoundingClientRect().top-s.getBoundingClientRect().top-140;},selector);
const checks=[];
for(const [width,theme]of [[390,'light'],[1440,'dark']]){
 await p.cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<640});await p.evaluate(x=>document.documentElement.dataset.theme=x,theme);
 const state=await p.evaluate(()=>{const old=document.querySelector('.ai-openui[data-read-only]'),latest=document.querySelector('.ai-openui:not([data-read-only])');return {oldDisabled:[...old.querySelectorAll('input:not([type=hidden]),select,textarea,.openui-button-base')].every(e=>e.matches(':disabled')),latestEnabled:!latest.querySelector('input[name=text]').matches(':disabled'),renderErrors:[...document.querySelectorAll('[role=status]')].some(e=>e.textContent.includes('未能'))};});assert(state.oldDisabled);assert(state.latestEnabled);assert(!state.renderErrors);
 await reveal('.ai-openui[data-read-only]');await p.screenshot({path:out+`/${width}-${theme}-history.png`});
 // Capture guards cover non-native sliders and even direct DOM event dispatch.
 const oldValue=await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [role=slider]').getAttribute('aria-valuenow'));await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [role=slider]').focus());await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [role=slider]').getAttribute('aria-valuenow')),oldValue);
 if(width===390){await reveal('.ai-openui[data-read-only] [role=slider]');const touch=await p.evaluate(()=>{const r=document.querySelector('.ai-openui[data-read-only] [role=slider]').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2,top:document.querySelector('[aria-label="对话"]>div').scrollTop};});await p.cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touch.x,y:touch.y}]});for(const dy of [30,60,90]){await p.cdp('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touch.x,y:touch.y-dy}]});await p.evaluate(()=>new Promise(requestAnimationFrame));}await p.cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await p.evaluate(top=>document.querySelector('[aria-label="对话"]>div').scrollTop>top,touch.top));assert.equal(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [role=slider]').getAttribute('aria-valuenow')),oldValue);}
 await p.evaluate(()=>{const el=document.querySelectorAll('.ai-openui[data-read-only] [role=tab]')[1],s=document.querySelector('[aria-label="对话"]>div');s.scrollTop+=el.getBoundingClientRect().top-s.getBoundingClientRect().top-140;});await p.click('.ai-openui[data-read-only] [role=tab] >> nth=1');await p.waitForFunction(()=>document.querySelector('.ai-openui[data-read-only] [role=tabpanel][data-state=active]')?.innerText.includes('第二视图'));
 if(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] button[aria-label="Next page"]').disabled))await p.click('.ai-openui[data-read-only] button[aria-label="Previous page"]');
 await p.click('.ai-openui[data-read-only] button[aria-label="Next page"]');assert(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] table').innerText.includes('记录11')));
 assert(await p.evaluate(()=>{const e=document.querySelector('.ai-openui[data-read-only] .openui-table-container');e.scrollLeft=50;return e.scrollLeft>0;}));
 const wasOpen=await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [data-mobile-editable] details:nth-child(2)').open);await reveal('.ai-openui[data-read-only] [data-mobile-editable] details:nth-child(2) summary');await p.click('.ai-openui[data-read-only] [data-mobile-editable] details:nth-child(2) summary');assert.notEqual(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] [data-mobile-editable] details:nth-child(2)').open),wasOpen);
 const expanded=await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] .openui-accordion-trigger').getAttribute('aria-expanded'));await p.evaluate(()=>{const el=document.querySelector('.ai-openui[data-read-only] .openui-accordion-trigger'),s=document.querySelector('[aria-label="对话"]>div');s.scrollTop+=el.getBoundingClientRect().top-s.getBoundingClientRect().top-140;});await p.click('.ai-openui[data-read-only] .openui-accordion-trigger');assert.notEqual(await p.evaluate(()=>document.querySelector('.ai-openui[data-read-only] .openui-accordion-trigger').getAttribute('aria-expanded')),expanded);assert(await p.evaluate(()=>!document.querySelector('.ai-openui[data-read-only] button[aria-label="Copy code"]').matches(':disabled')));
 const latestRange=await p.evaluate(()=>Number(document.querySelector('.ai-openui:not([data-read-only]) [role=slider]').getAttribute('aria-valuenow')));await p.focus('.ai-openui:not([data-read-only]) [role=slider]');await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>Number(document.querySelector('.ai-openui:not([data-read-only]) [role=slider]').getAttribute('aria-valuenow'))),latestRange+1);
 await p.fill('.ai-openui:not([data-read-only]) input[name=text]','最新可编辑');await p.selectOption('.ai-openui:not([data-read-only]) select[name=choice]','b');
 await p.screenshot({path:out+`/${width}-${theme}.png`});checks.push({width,theme,...state,views:true,latestEditing:true});
}
await p.evaluate(()=>{window.__readonlyRequests=[];const original=window.fetch;window.fetch=async(...args)=>{if(String(args[0]).includes('/api/ai-chat')){window.__readonlyRequests.push(JSON.parse(args[1].body));const response=new Response([{role:'assistant'},{content:'root = Stack([Form("next",Buttons([Button("下一步",Action([@ToAssistant("下一步")]))]),[FormControl("新输入",Input("next-input","请输入"))])])'},{}].map((delta,i)=>JSON.stringify({choices:[{index:0,delta,finish_reason:i===2?'stop':null}]})).join('\n')+'\n',{headers:{'Content-Type':'application/x-ndjson'}});return new Promise(resolve=>{window.__releaseReadOnly=()=>resolve(response);});}return original(...args);};document.querySelector('.ai-openui[data-read-only] .openui-button-base').dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));});assert.equal(await p.evaluate(()=>window.__readonlyRequests.length),0);
await p.click('.ai-openui:not([data-read-only]) button:text-is("提交当前信息")');await p.waitForFunction(()=>window.__readonlyRequests.length===1);assert(await p.evaluate(()=>[...document.querySelectorAll('input[name=text]')].every(e=>e.matches(':disabled'))));await p.click('.ai-openui[data-read-only] button[aria-label="Previous page"] >> nth=0');await p.evaluate(()=>window.__releaseReadOnly());await p.waitForFunction(()=>!document.querySelector('[data-generation-status]')); assert(await p.evaluate(()=>[...document.querySelectorAll('input[name=text]')].every(e=>e.matches(':disabled'))));assert(await p.evaluate(()=>!document.querySelector('input[name="next-input"]').matches(':disabled')));
await p.reload();await p.waitForSelector('input[name="next-input"]');assert(await p.evaluate(()=>[...document.querySelectorAll('input[name=text]')].every(e=>e.matches(':disabled'))));assert(await p.evaluate(()=>[...document.querySelectorAll('input[name=text]')].at(-1).value==='最新可编辑'));
await p.cdp('Emulation.clearDeviceMetricsOverride');await fs.writeFile(out+'/result.json',JSON.stringify({passed:true,checks,oldActionBlocked:true,latestSubmissionLocksPrevious:true,persisted:true},null,2)+'\n');console.log(checks);
JS
} | ego-browser nodejs
