#!/bin/sh
# Verify visible message/context separation with the official action path.
set -eu
{
node --input-type=module <<'CONFIG'
const base=process.env.DESIGN_BASE_URL;if(!/^http:\/\/localhost:\d+$/.test(base||''))throw Error('Use isolated localhost');console.log('const config='+JSON.stringify({base,space:Number(process.env.EGO_TASK_SPACE),root:process.cwd()})+';');
CONFIG
cat <<'JS'
const assert=(await import('node:assert/strict')).default,fs=await import('node:fs/promises');const t=await taskSpace(config.space),p=t.page('p1'),out=config.root+'/docs/design/execution/evidence/ai-chat-submission';await fs.mkdir(out,{recursive:true});
const response='root = Stack([Form("资料", Buttons([Button("确认提交", Action([@ToAssistant("提交需求")]))]), [FormControl("名称",Input("名称","请输入","text",null,"演示客户")),FormControl("备注",TextArea("备注","请输入",3,null,"完整的表单备注")),FormControl("数量",Slider("数量","continuous",0,10,1,[0],"数量")),FormControl("通知",SwitchGroup("通知",[SwitchItem("开启提醒","","提醒",false)]))])])';
const fixture={id:'submission-fixture',agentId:'general',title:'提交展示检查',messages:[{id:'form',role:'assistant',parts:[{type:'text',text:response}]}]};
await p.goto(config.base+'/robots.txt');await p.evaluate(c=>{const k='personal-design:ai-chat:v1';if(JSON.parse(localStorage.getItem(k)||'{}').conversations?.some(x=>x.id!=='submission-fixture'))throw Error('User records');localStorage.setItem(k,JSON.stringify({agents:[],conversations:[c]}));},fixture);await p.goto(config.base+'/products/ai-chat');await p.waitForSelector('input[name="名称"]');
await p.cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await p.fill('input[name="名称"]','已提交客户名称');await p.fill('textarea[name="备注"]','更新后的完整表单备注');await p.focus('[role=slider]');await p.keyboard.press('ArrowRight');await p.keyboard.press('Home');await p.click('[role=switch]');await p.click('[role=switch]');
await p.evaluate(()=>{window.__submissionRequests=[];const original=window.fetch;window.fetch=async(...args)=>{if(String(args[0]).includes('/api/ai-chat')){window.__submissionRequests.push(JSON.parse(args[1].body));return new Response([{role:'assistant'},{content:'root = Stack([TextContent("已收到提交，可以继续追问。")])'},{}].map((delta,i)=>JSON.stringify({choices:[{index:0,delta,finish_reason:i===2?'stop':null}]})).join('\n')+'\n',{headers:{'Content-Type':'application/x-ndjson'}});}return original(...args);};});
await p.click('button:text-is("确认提交")');await p.waitForFunction(()=>window.__submissionRequests.length===1&&!document.querySelector('[data-generation-status]'));
const submitted=await p.evaluate(()=>window.__submissionRequests[0].messages.at(-1));assert.equal(submitted.parts[0].text,'提交需求');assert(submitted.metadata.submission);const data=JSON.stringify(submitted.metadata.submission.formState);assert(data.includes('已提交客户名称')&&data.includes('更新后的完整表单备注')&&data.includes('[0]')&&data.includes(':false'));
assert(await p.evaluate(()=>{const e=document.querySelector('article[aria-label="你的问题"]');return !e.innerText.includes('已提交客户名称')&&!e.querySelector('details').open;}));await p.screenshot({path:out+'/collapsed-mobile.png'});
await p.click('article[aria-label="你的问题"] summary');assert(await p.evaluate(()=>document.querySelector('article[aria-label="你的问题"]').innerText.includes('已提交客户名称')));await p.screenshot({path:out+'/expanded-mobile.png'});await p.click('article[aria-label="你的问题"] summary');
await p.click('button[aria-label="重新生成"]');await p.waitForFunction(()=>window.__submissionRequests.length===2&&!document.querySelector('[data-generation-status]'));assert.deepEqual(await p.evaluate(()=>window.__submissionRequests[1].messages.at(-1).metadata.submission),submitted.metadata.submission);
if(await p.evaluate(()=>!!document.querySelector('button[aria-label="回到最新消息"]')))await p.click('button[aria-label="回到最新消息"]');await p.fill('textarea[aria-label^="发消息给"]','继续追问');await p.click('button[aria-label="发送消息"]');await p.waitForFunction(()=>window.__submissionRequests.length===3&&!document.querySelector('[data-generation-status]'));assert(await p.evaluate(()=>window.__submissionRequests[2].messages.some(m=>m.metadata?.submission)));assert(await p.evaluate(()=>!window.__submissionRequests[2].messages.at(-1).metadata?.submission));
await p.reload();await p.waitForSelector('article[aria-label="你的问题"] details');assert(await p.evaluate(()=>{const e=document.querySelector('article[aria-label="你的问题"]');return e.querySelector('p').textContent==='提交需求'&&!e.querySelector('details').open&&!e.innerText.includes('已提交客户名称');}));await p.click('article[aria-label="你的问题"] summary');assert(await p.evaluate(()=>document.querySelector('article[aria-label="你的问题"]').innerText.includes('已提交客户名称')));
await p.cdp('Emulation.clearDeviceMetricsOverride');await fs.writeFile(out+'/result.json',JSON.stringify({passed:true,displayText:'提交需求',structuredValues:true,collapsedByDefault:true,viewableReceipt:true,retryPreservesContext:true,followupPreservesContext:true,reloadPreservesContext:true},null,2)+'\n');console.log('submission display, typed context, retry, followup and reload passed');
JS
} | ego-browser nodejs
