#!/bin/sh
set -eu
{
node --input-type=module <<'CONFIG'
console.log('const config='+JSON.stringify({space:Number(process.env.EGO_TASK_SPACE),root:process.cwd()})+';');
CONFIG
cat <<'JS'
const assert=(await import('node:assert/strict')).default;const fs=await import('node:fs/promises');const t=await taskSpace(config.space),p=t.page('p1');const out=config.root+'/docs/design/execution/evidence/ai-chat-catalog';const checks=[];const settle=()=>p.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
await p.cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
const makeLatest=async id=>{await p.evaluate(id=>{const k='personal-design:ai-chat:v1',s=JSON.parse(localStorage.getItem(k));if(s.conversations.some(c=>!['component-fixture','contract-fixture'].includes(c.id)))throw Error('Not test records');const c=s.conversations[0],i=c.messages.findIndex(m=>m.id===id);if(i<0)throw Error('Missing test message');c.messages.push(...c.messages.splice(i,1));localStorage.setItem(k,JSON.stringify(s));},id);await p.reload();await p.waitForSelector('.ai-openui');};
await makeLatest('catalog-7');
const before=await p.evaluate(()=>document.querySelector('[role=switch]').getAttribute('aria-checked'));await p.click('[role=switch]');assert.notEqual(await p.evaluate(()=>document.querySelector('[role=switch]').getAttribute('aria-checked')),before);checks.push('switch changes state within a 44px target');
await makeLatest('catalog-5');await p.focus('.openui-option-card >> nth=0');await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');assert(await p.evaluate(()=>document.activeElement.matches('.openui-option-card:focus-visible')&&getComputedStyle(document.activeElement).outlineStyle!=='none'));checks.push('option cards retain keyboard focus');
await makeLatest('catalog-2');await p.click('button:text-is("Submit")');await p.waitForSelector('.openui-hint-error');assert(await p.evaluate(()=>[...document.querySelectorAll('.openui-hint-error')].every(e=>getComputedStyle(e).fontSize==='12px')));checks.push('validation hints use 12px');await settle();await p.screenshot({path:out+'/validation.png'});
assert(await p.evaluate(()=>getComputedStyle(document.querySelector('.openui-code-block-copy-button')).opacity==='1'));checks.push('code copy is visible without hover');
await p.evaluate(()=>{document.querySelector('[aria-label="对话"]>div').scrollTop=0;});await p.click('[aria-controls="ai-agent-list"]');await p.waitForSelector('#ai-agent-list:popover-open');await settle();await p.screenshot({path:out+'/agents.png'});await p.click('button:text-is("创建智能体")');await p.waitForSelector('#agent-creation-title');await settle();await p.screenshot({path:out+'/create.png'});assert(await p.evaluate(()=>{const m=document.querySelector('main').getBoundingClientRect(),h=document.querySelector('#agent-creation-title').getBoundingClientRect();const title=document.querySelector('#agent-creation-title');return title.contains(document.elementFromPoint(h.left+h.width/2,h.top+h.height/2))&&h.left>=m.left&&h.right<=m.right&&getComputedStyle(document.querySelector('#agent-creation-title')).fontSize==='15px';}));await p.click('[aria-label="返回智能体列表"]');await p.keyboard.press('Escape');await p.click('[aria-label="打开导航"]');await p.waitForSelector('dialog[open]');await settle();await p.screenshot({path:out+'/navigation.png'});await p.keyboard.press('Escape');checks.push('agent picker, creation screen and drawer stay within phone geometry');
await p.click('.openui-gallery__image');await p.waitForSelector('.openui-gallery__modal');assert(await p.evaluate(()=>getComputedStyle(document.querySelector('.openui-gallery__modal')).getPropertyValue('--answer-caption-size').trim()==='12px'));await settle();await p.screenshot({path:out+'/gallery.png'});await p.click('[aria-label="Close gallery"]');checks.push('gallery portal retains shared font tokens');
// Only rewrite the dedicated catalog fixture; preserve any user storage.
await p.evaluate(()=>{const k='personal-design:ai-chat:v1',s=JSON.parse(localStorage.getItem(k));if(s.conversations.some(c=>c.id!=='component-fixture'))throw Error('Not catalog storage');for(const m of s.conversations[0].messages)for(const part of m.parts)if(part.type==='text')part.text=part.text.replace('Modal("弹出内容", false','Modal("弹出内容", true');localStorage.setItem(k,JSON.stringify(s));});await p.reload();await p.waitForSelector('.openui-modal-content');
for(const theme of ['light','dark']){await p.evaluate(x=>document.documentElement.dataset.theme=x,theme);await p.waitForFunction(()=>getComputedStyle(document.querySelector('.openui-modal-body p')).fontSize==='13px');assert(await p.evaluate(()=>{const e=document.querySelector('.openui-modal-content'),r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&getComputedStyle(e).getPropertyValue('--answer-caption-size').trim()==='12px';}));await settle();await p.screenshot({path:out+'/modal-'+theme+'.png'});}await p.keyboard.press('Escape');await p.waitForSelector('.openui-modal-content',{state:'hidden'});checks.push('official modal inherits answer tokens in both themes and closes with Escape');
await fs.writeFile(out+'/states.json',JSON.stringify({passed:true,checks},null,2)+'\n');console.log(checks);await p.cdp('Emulation.clearDeviceMetricsOverride');
JS
} | ego-browser nodejs
