#!/bin/sh
# Filled and focused controls, rather than placeholder-only screenshots.
set -eu
{
node --input-type=module <<'CONFIG'
const base=process.env.DESIGN_BASE_URL;if(!/^http:\/\/localhost:\d+$/.test(base||''))throw Error('Use isolated localhost');console.log('const config='+JSON.stringify({base,space:Number(process.env.EGO_TASK_SPACE),root:process.cwd()})+';');
CONFIG
cat <<'JS'
const fs=await import('node:fs/promises'),assert=(await import('node:assert/strict')).default;const t=await taskSpace(config.space),p=t.page('p1');const out=config.root+'/docs/design/execution/evidence/ai-chat-input-values';await fs.mkdir(out,{recursive:true});
const response=`root = Stack([CardHeader("输入值统一检查", "已填写和聚焦状态"), Form("values", Buttons([Button("继续", Action([@ToAssistant("继续")]))]), [FormControl("文本", Input("text", "输入提示", "text", null, "已填写的中文内容")),FormControl("邮件", Input("email", "邮箱提示", "email", null, "hello@example.com")),FormControl("密码",Input("password","密码提示","password",null,"example")),FormControl("数值",Input("number","数值提示","number",null,"85")),FormControl("网址",Input("url","网址提示","url",null,"https://example.com")),FormControl("多行",TextArea("notes","多行提示",3,null,"已填写的多行内容")),FormControl("已选",Select("selected",[SelectItem("one","已选内容")],"请选择",null,"one")),FormControl("待选",Select("empty",[SelectItem("one","候选内容")],"请选择")),FormControl("日期",DatePicker("date","single",null,"2026-10-05")),FormControl("日期范围",DatePicker("range","range",null,{from:"2026-10-05",to:"2026-10-10"})),FormControl("滑块",Slider("continuous","continuous",0,100,1,[50],"比例")),FormControl("离散数值",Slider("discrete","discrete",0,100,10,[50],"档位"))]),EditableTable("编辑数据",[{type:"text",key:"text",header:"编辑文本"},{type:"number",key:"number",header:"编辑数值"},{type:"url",key:"url",header:"编辑网址"},{type:"select",key:"select",header:"编辑选择",options:[{value:"one",label:"编辑选中值"}]},{type:"date-single",key:"date",header:"编辑日期"}],[{id:"one",values:["编辑内容",42,"https://example.com","one","2026-10-05"]}])])`;
const fixture={id:'input-fixture',agentId:'general',title:'输入检查',messages:[{id:'input-response',role:'assistant',parts:[{type:'text',text:response}]}]};
await p.goto(config.base+'/products/ai-chat');await p.evaluate(c=>{const key='personal-design:ai-chat:v1';if(JSON.parse(localStorage.getItem(key)||'{}').conversations?.some(x=>!['case-fixture','component-fixture','input-fixture'].includes(x.id)))throw Error('User records');localStorage.setItem(key,JSON.stringify({agents:[],conversations:[c]}));},fixture);await p.reload();await p.waitForSelector('[data-mobile-editable]');
const results=[];
for(const [width,theme] of [[320,'light'],[390,'dark'],[1440,'light']]){
 await p.cdp('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<640});await p.evaluate(x=>document.documentElement.dataset.theme=x,theme);
 const fields=await p.evaluate(()=>[...document.querySelectorAll('.ai-openui input:not([type=checkbox]):not([type=radio]):not([type=hidden]),.ai-openui textarea,.ai-openui select,.ai-openui .openui-select-trigger')].map(e=>{const empty=e.tagName==='SELECT'&&!e.value;const normal=getComputedStyle(e).fontSize;e.focus();const focused=getComputedStyle(e).fontSize;const date=e.type==='date'?getComputedStyle(e,'::-webkit-datetime-edit').fontSize:null;e.blur();return {type:e.type||e.role,name:e.name||e.getAttribute('aria-label'),empty,normal,focused,date,height:e.getBoundingClientRect().height};}));
 assert(fields.length>=17);for(const f of fields){assert.equal(f.normal,'13px',JSON.stringify(f));assert.equal(f.focused,f.normal);if(f.date)assert.equal(f.date,'13px');assert(f.height>=44);}
 assert(await p.evaluate(()=>!document.querySelector('[role=status]')?.textContent.includes('未能')&&document.documentElement.scrollWidth<=innerWidth));
 await p.fill('input[name=text]','真实键入的内容');await p.fill('[aria-label^="发消息给"]','追问输入');assert.equal(await p.evaluate(()=>getComputedStyle(document.querySelector('[aria-label^="发消息给"]')).fontSize),'13px');await p.fill('[aria-label^="发消息给"]','');
 await p.evaluate(()=>{const s=document.querySelector('[aria-label="对话"]>div');s.scrollTop=0;});await p.screenshot({path:out+`/${width}-${theme}.png`});results.push({width,theme,fields});
}
await p.reload();await p.waitForSelector('input[name=text]');assert.equal(await p.evaluate(()=>document.querySelector('input[name=text]').value),'真实键入的内容');
await p.evaluate(()=>document.querySelector('[aria-label="对话"]>div').scrollTop=0);await p.click('[aria-controls="ai-agent-list"]');await p.click('button:text-is("创建智能体")');await p.waitForSelector('#agent-creation input');await p.fill('#agent-creation input','测试智能体');await p.fill('#agent-creation textarea','这是测试提示词');assert(await p.evaluate(()=>[...document.querySelectorAll('#agent-creation input,#agent-creation textarea')].every(e=>getComputedStyle(e).fontSize==='13px')));await p.click('[aria-label="返回智能体列表"]');await p.keyboard.press('Escape');
await p.evaluate(()=>{const k='personal-design:ai-chat:v1',s=JSON.parse(localStorage.getItem(k));const c=s.conversations.find(c=>c.id==='input-fixture');c.messages=[{id:'portal',role:'assistant',parts:[{type:'text',text:'root = Stack([Modal("弹层输入", true, [Form("popup", Buttons([Button("继续", Action([@ToAssistant("继续")]))]), [FormControl("文本",Input("portal-text","弹层占位","text",null,"弹层已填值"))])])])'}]}];localStorage.setItem(k,JSON.stringify(s));});await p.reload();await p.waitForSelector('.openui-modal-content input');assert(await p.evaluate(()=>{const e=document.querySelector('.openui-modal-content input');return getComputedStyle(e).fontSize==='13px'&&getComputedStyle(e,'::placeholder').fontSize==='13px';}));await p.keyboard.press('Escape');
await p.cdp('Emulation.clearDeviceMetricsOverride');await fs.writeFile(out+'/result.json',JSON.stringify({passed:true,results,composer:'13px',agentFields:'13px',portalValue:'13px',portalPlaceholder:'13px',persistence:true},null,2)+'\n');console.log(results.map(r=>({width:r.width,theme:r.theme,fieldCount:r.fields.length,filled:'13px',empty:'13px'})));
JS
} | ego-browser nodejs
