/** Public design-engineering tool directory. Generated by scripts/sync.ts. */
import rawCatalog from '../catalog.json';

interface ToolEntry {
  name: string;
  url: string;
  /** 同步时下载到 apps/web/public 的 favicon。 */
  icon: string | null;
}

interface ToolCategory {
  /** Stable source heading used for filtering and synchronization. */
  id: string;
  tools: ToolEntry[];
}

interface ToolCatalog {
  sourceUrl: string;
  syncedAt: string;
  categories: ToolCategory[];
}

const toolCatalog = rawCatalog as ToolCatalog;
export const toolCategories = toolCatalog.categories;

/** A compact, varied live-content preview for the portfolio timeline. */
export const toolPreview = toolCategories
  .slice(0, 4)
  .flatMap((category) => category.tools.slice(0, 1));
